name: build all PDF
on:
  push:
    tags:
      - '*'
  workflow_dispatch:  # allows manual running of the workflow
  
jobs:
  build-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for creating releases
    steps:
      - uses: actions/checkout@v5
      - name: Set up Mise
        uses: jdx/mise-action@v3
      - name: Install TeX packages
        run: mise run install-tex-packages
      - name: Find and build all LaTeX projects
        run: |
          projects=$(find . -type f -name 'main.tex' -exec dirname {} \;)
          mkdir -p artifacts
          for project in $projects; do
            echo "Building project in $project"
            cd "$project"
            mise run build
            pdf_name="$(
              [ "$project" = "." ] && echo ${{ github.event.repository.name }} ||
              basename "$project"
            ).pdf"
            cd -
            mv "$project/build/main.pdf" "artifacts/$pdf_name"
          done
      - name: Tag if on branch
        if: github.ref_type == 'branch'
        run: |
          git tag -f ${{ github.ref_name }}
          git push origin refs/tags/${{ github.ref_name }} --force
      - name: Release all PDFs
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: 'artifacts/**/*.pdf'
