name: build PDF
on:
  push:
    tags:
      - '*'
  workflow_dispatch:  # allows manual running of the workflow
  
jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}
    steps:
      - uses: actions/checkout@v5
      - run: |
          projects=$(find . -type f -name 'main.tex' -exec dirname {} \;)
          json=$(echo "$projects" | jq -R -s -c '
            split("\n") | map({
              folder: .,
              name: (
                if . == "." then "${{ github.event.repository.name }}"
                else (split("/") | last) end
              )
            )'
          )
          echo "projects=$json" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: discover
    strategy:
      matrix:
        project: ${{ fromJson(needs.discover.outputs.projects) }}
    steps:
      - uses: actions/checkout@v5
      # Set up Mise
      - uses: jdx/mise-action@v3
      # Install tex packages
      - name: Install TeX packages
        run: mise run install-tex-packages
      - name: Build PDF for ${{ matrix.project.name }}
        run: |
          cd "${{ matrix.project.folder }}"
          mise run build -jobname "${{ matrix.project.name }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.name }}
          path: "${{ matrix.project.folder }}/build/*.pdf"

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write  # needed for creating releases
    steps:
      - uses: actions/checkout@v5
      - name: Tag if on branch
        if: github.ref_type == 'branch'
        run: |
          git tag -f ${{ github.ref_name }}
          git push origin refs/tags/${{ github.ref_name }} --force
      - name: Download built PDFs
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      # Create or update release and upload PDF
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: 'artifacts/**/*.pdf'
